server:
  port: 9999

app:
  datasource:
    main:
      jdbc-url: jdbc:mysql://localhost:3306/microservices
      username: root
      password: prasad@mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-size : 30

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring:
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql : true
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
    open-in-view: false      
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: init
    baseline-version: 0
  main:
    allow-bean-definition-overriding : true
